copy \a\hd4\AmiArcadia\source\debugger.c .
copy \a\hd4\AmiArcadia\source\engine1.c  .
copy \a\hd4\AmiArcadia\source\engine2.c  .
copy \a\hd4\AmiArcadia\source\arcadia.c  .
copy \a\hd4\AmiArcadia\source\interton.c .
copy \a\hd4\AmiArcadia\source\elektor.c  .
copy \a\hd4\AmiArcadia\source\pipbug.c   .
copy \a\hd4\AmiArcadia\source\instruct.c .
copy \a\hd4\AmiArcadia\source\cd2650.c   .
copy \a\hd4\AmiArcadia\source\malzak.c   .
copy \a\hd4\AmiArcadia\source\zaccaria.c .
copy \a\hd4\AmiArcadia\source\chaos.c    .
copy \a\hd4\AmiArcadia\source\dolphin.c  .
copy \a\hd4\AmiArcadia\source\phunsy.c   .
copy \a\hd4\AmiArcadia\source\pong.c     .
copy \a\hd4\AmiArcadia\source\selbst.c   .
copy \a\hd4\AmiArcadia\source\mikit.c    .
copy \a\hd4\AmiArcadia\source\tr.c       .
copy \a\hd4\AmiArcadia\source\2650.c     .
copy \a\hd4\AmiArcadia\source\6802.c     .
copy \a\hd4\AmiArcadia\source\pvi.c      .
copy \a\hd4\AmiArcadia\source\unzip.c    .
copy \a\hd4\AmiArcadia\source\aa.h       .
copy \a\hd4\AmiArcadia\source\engine1.h  .
copy \a\hd4\AmiArcadia\source\games.h    .
copy \a\hd4\AmiArcadia\source\labels.h   .
copy \a\hd4\AmiArcadia\source\engine2.h  .
copy \a\hd4\AmiArcadia\source\overlays.h .
copy \a\hd4\AmiArcadia\source\arcadia.h  .
copy \a\hd4\AmiArcadia\source\interton.h .
copy \a\hd4\AmiArcadia\source\elektor.h  .
copy \a\hd4\AmiArcadia\source\pipbug.h   .
copy \a\hd4\AmiArcadia\source\instruct.h .
copy \a\hd4\AmiArcadia\source\cd2650.h   .
copy \a\hd4\AmiArcadia\source\malzak.h   .
copy \a\hd4\AmiArcadia\source\zaccaria.h .
copy \a\hd4\AmiArcadia\source\chaos.h    .
copy \a\hd4\AmiArcadia\source\phunsy.h   .
copy \a\hd4\AmiArcadia\source\tr.h       .
