// INCLUDES---------------------------------------------------------------

#include "da.h"

#include <stdio.h>
#include <stdlib.h> // EXIT_SUCCESS, EXIT_FAILURE
#include <string.h>

// DEFINES----------------------------------------------------------------

#define DOUBLEWIDTH
// whether to ever widen screenshots

#define SCREENPTR(x,y)  *(screenptr + (x * BOXHEIGHT) + y)

#define GIFTABLESIZE    (32 * 3) // for 32 colours

#define HT_KEY_MASK     0x1FFF   /* 13 bit key mask */
#define HT_GET_KEY(x)   ((x) >> 12)
#define HT_GET_CODE(x)  ((x) & 0x0FFF)
#define HT_PUT_KEY(x)   ((x) << 12)
#define HT_PUT_CODE(x)  ((x) & 0x0FFF)
#define LZ_MAX_CODE     4095     /* Largest 12 bit code */
#define FLUSH_OUTPUT    4096     /* Impossible code = flush */
#define FIRST_CODE      4097     /* Impossible code = first */
#define HT_SIZE         8192     /* 13 bit hash table size */
#define IMAGE_SAVING    0        /* file_state = processing */
#define IMAGE_COMPLETE  1        /* finished writing */

typedef struct
{   int depth,
        clear_code, eof_code,
        running_code, running_bits,
        max_code_plus_one,
        prev_code, current_code,
        stack_ptr,
        shift_state;
    unsigned long shift_data;
    unsigned long pixel_count;
    int           file_state, position, bufsize;
    unsigned char buf[256];
    unsigned long hash_table[HT_SIZE];
} GifEncoder;

#define MAXRUN_SKIP   127

/* Packer modes. */

#define DUMP            0
#define RUN             1

/* Minimum data run size, maximum data run size and maximum cache size. */

#define MINRUN          3
#define MAXRUN_PACKER 128
#define MAXDAT        128

/* EXPORTED VARIABLES-----------------------------------------------------

(None)

IMPORTED VARIABLES----------------------------------------------------- */

IMPORT int                      colourset,
                                machine,
                                offset,
                                wide;
IMPORT UBYTE*                   IOBuffer;
IMPORT ASCREEN                  screen[BOXWIDTH][BOXHEIGHT];
IMPORT struct MachineStruct     machines[MACHINES];
IMPORT const UWORD              pencolours[4][GUESTCOLOURS];

// MODULE VARIABLES-------------------------------------------------------

MODULE FLAG                     widening;
MODULE ASCREEN*                 screenptr;
MODULE UBYTE                    wideline[BOXWIDTH * 2];
MODULE int                      picwidth;

/* MODULE ARRAYS----------------------------------------------------------

(None)

MODULE STRUCTURES---------------------------------------------------------

(None)

MODULE FUNCTIONS------------------------------------------------------- */

MODULE void write_gif_line(GifEncoder* encoder, int width);
MODULE int lookup_gif_hash(unsigned long* hash_table, unsigned long key);
MODULE void write_gif_code(GifEncoder* encoder, int code);
MODULE int gif_hash_key(unsigned long key);
MODULE void add_gif_hash_entry(unsigned long* hash_table, unsigned long key, int code);
MODULE void write_gif_byte(GifEncoder* encoder, int ch);
MODULE void init_gif_encoder(GifEncoder* encoder, int depth);
MODULE void flush_gif_encoder(GifEncoder* encoder);
MODULE UBYTE getred(int whichcolourset, int whichpen);
MODULE UBYTE getgreen(int whichcolourset, int whichpen);
MODULE UBYTE getblue(int whichcolourset, int whichpen);

// CODE-------------------------------------------------------------------

JNIEXPORT jbyteArray JNICALL Java_com_amigan_droidarcadia_OptionsActivity_savescreenshot(JNIEnv* env, jobject this)
{   TRANSIENT UBYTE*     TheBody;
    TRANSIENT int        bodysize,
                         count,
                         i, j,
                         length,
                         x, y;
    TRANSIENT TEXT       commentstring[50 + 1];
    TRANSIENT jintArray  rc;
    PERSIST   GifEncoder encoder; // PERSISTent so as not to blow the stack

PERSIST UBYTE gif_header[13] =
{   0x47, 0x49, 0x46, 0x38, 0x37, 0x61, //  0..  5 "GIF87a"
    0x00, 0x00,                         //  6..  7 width
    0x00, 0x00,                         //  8..  9 height
    0xC4,                               // 10      colour depth, etc. ($C4 means 5 bitplanes)
    0x00,                               // 11      background colour index
    0x00                                // 12      pixel aspect ratio
};

    // assert(GUESTCOLOURS == 24);

    screenptr = &screen[0][0];
    picwidth = machines[machine].width;
    widening = FALSE;
#ifdef DOUBLEWIDTH
    picwidth *= 2;
    widening = TRUE;
#endif

    sprintf((char*) commentstring, "Generated by DroidArcadia");
    length = strlen((const char*)commentstring);

    // header
    gif_header[6] = picwidth  % 256;
    gif_header[7] = picwidth  / 256;
    gif_header[8] = machines[machine].height % 256;
    gif_header[9] = machines[machine].height / 256;

    IOBuffer = malloc(48 * KILOBYTE); // should check return code
    
    for (i = 0; i < 13; i++)
    {   IOBuffer[i] = gif_header[i];
    }

    // palette
    for (i = 0; i < 24; i++)
    {   IOBuffer[13 + (i * 3)] = getred(colourset, i);
        IOBuffer[14 + (i * 3)] = getgreen(colourset, i);
        IOBuffer[15 + (i * 3)] = getblue(colourset, i);
    }

    offset = 13 + GIFTABLESIZE;

    IOBuffer[offset++] = 0x21; // GIF Extension code
    IOBuffer[offset++] = 0xFE; // Comment Label
    IOBuffer[offset++] = length; // Length of Comment
    for (j = 0; j < length; j++)
    {   IOBuffer[offset++] = commentstring[j];
    }
    IOBuffer[offset++] = 0x00; // Data Sub-block Terminator

    // image descriptor block
    IOBuffer[offset++] = 0x2C; // block code
    IOBuffer[offset++] = 0;
    IOBuffer[offset++] = 0; // left
    IOBuffer[offset++] = 0;
    IOBuffer[offset++] = 0; // top
    IOBuffer[offset++] = gif_header[6];
    IOBuffer[offset++] = gif_header[7];
    IOBuffer[offset++] = gif_header[8];
    IOBuffer[offset++] = gif_header[9];
    IOBuffer[offset++] = 0;

    // body
    init_gif_encoder(&encoder, 5); // 5 bitplanes
    for (y = 0; y < machines[machine].height; y++)
    {   i = 0;
        for (x = 0; x < machines[machine].width; x++)
        {   wideline[i++] = SCREENPTR(x, y);
            if (widening)
            {   wideline[i++] = SCREENPTR(x, y);
        }   }
        write_gif_line(&encoder, picwidth);
    }
    flush_gif_encoder(&encoder);

    IOBuffer[offset++] = 0x3B; // EOF

    rc = (*env)->NewByteArray(env, offset);
    (*env)->SetByteArrayRegion(env, rc, 0, offset, (const jbyte*) IOBuffer);
    free(IOBuffer);
    
    return rc;
}

MODULE void write_gif_line(GifEncoder* encoder, int width)
{   int            current_code, new_code,
                   i,
                   x = 0;
    unsigned long  new_key;
    unsigned char  pixval;

    if (encoder->current_code == FIRST_CODE)
        current_code = wideline[x++];
    else
        current_code = encoder->current_code;

    while (x < width)
    {   pixval = wideline[x++];

        new_key = (((unsigned long) current_code) << 8) + pixval;
        if ((new_code = lookup_gif_hash(encoder->hash_table, new_key)) >= 0)
        {   current_code = new_code;
        } else
        {   write_gif_code(encoder, current_code);
            current_code = pixval;

            if (encoder->running_code >= LZ_MAX_CODE)
            {   write_gif_code(encoder, encoder->clear_code);
                encoder->running_code = encoder->eof_code + 1;
                encoder->running_bits = encoder->depth + 1;
                encoder->max_code_plus_one = 1 << encoder->running_bits;
                for (i = 0; i < HT_SIZE; i++)
                {   encoder->hash_table[i] = 0xFFFFFFFF;
            }   }
            else
            {   add_gif_hash_entry(encoder->hash_table, new_key, encoder->running_code++);
    }   }   }

    encoder->current_code = current_code;
}
MODULE int lookup_gif_hash(unsigned long *hash_table, unsigned long key)
{   int hkey = gif_hash_key(key);
    unsigned long htkey;

    while ((htkey = HT_GET_KEY(hash_table[hkey])) != 0xFFFFFL)
    {   if (key == htkey)
        {   return (int) HT_GET_CODE(hash_table[hkey]);
        }
        hkey = (hkey + 1) & HT_KEY_MASK;
    }
    return -1;
}
MODULE void write_gif_code(GifEncoder* encoder, int code)
{   if (code == FLUSH_OUTPUT)
    {   while (encoder->shift_state > 0)
        {   write_gif_byte(encoder, encoder->shift_data & 0xff);
            encoder->shift_data >>= 8;
            encoder->shift_state -= 8;
        }
        encoder->shift_state = 0;
        write_gif_byte(encoder, FLUSH_OUTPUT);
    } else
    {   encoder->shift_data |= ((long) code) << encoder->shift_state;
        encoder->shift_state += encoder->running_bits;
        while (encoder->shift_state >= 8)
        {   write_gif_byte(encoder, encoder->shift_data & 0xff);
            encoder->shift_data >>= 8;
            encoder->shift_state -= 8;
    }   }

    if (encoder->running_code >= encoder->max_code_plus_one && code <= 4095)
    {   encoder->max_code_plus_one = 1 << ++encoder->running_bits;
}   }
MODULE int gif_hash_key(unsigned long key)
{   return (int) (((key >> 12) ^ key) & HT_KEY_MASK);
}
MODULE void add_gif_hash_entry(unsigned long* hash_table, unsigned long key, int code)
{   int hkey = gif_hash_key(key);

    while (HT_GET_KEY(hash_table[hkey]) != 0xFFFFFL)
    {   hkey = (hkey + 1) & HT_KEY_MASK;
    }
    hash_table[hkey] = HT_PUT_KEY(key) | HT_PUT_CODE(code);
}
MODULE void write_gif_byte(GifEncoder* encoder, int ch)
{   int            i;
    unsigned char* buf = encoder->buf;

    if (encoder->file_state == IMAGE_COMPLETE)
        return;

    if (ch == FLUSH_OUTPUT)
    {   if (encoder->bufsize)
        {   IOBuffer[offset++] = encoder->bufsize;
            for (i = 0; i < encoder->bufsize; i++)
            {   IOBuffer[offset++] = buf[i];
            }
            encoder->bufsize = 0;
        }
        IOBuffer[offset++] = 0;
        encoder->file_state = IMAGE_COMPLETE;
    } else
    {   if (encoder->bufsize == 255)
        {   IOBuffer[offset++] = encoder->bufsize;
            for (i = 0; i < encoder->bufsize; i++)
            {   IOBuffer[offset++] = buf[i];
            }
            encoder->bufsize = 0;
        }
        buf[encoder->bufsize++] = ch;
}   }
MODULE void init_gif_encoder(GifEncoder* encoder, int depth)
{   int i;

    /* if (depth < 2)
    {   depth = 2; // should never happen anyway
    } */

    encoder->file_state        = IMAGE_SAVING;
    encoder->position          = 0;
    encoder->bufsize           = 0;
    encoder->buf[0]            = 0;
    encoder->depth             = depth;
    encoder->clear_code        = 1 << depth;
    encoder->eof_code          = encoder->clear_code + 1;
    encoder->running_code      = encoder->eof_code + 1;
    encoder->running_bits      = depth + 1;
    encoder->max_code_plus_one = 1 << encoder->running_bits;
    encoder->current_code      = FIRST_CODE;
    encoder->shift_state       = 0;
    encoder->shift_data        = 0;

    IOBuffer[offset++] = depth;

    for (i = 0; i < HT_SIZE; i++)
    {   encoder->hash_table[i] = 0xFFFFFFFF;
    }

    write_gif_code(encoder, encoder->clear_code);
}
MODULE void flush_gif_encoder(GifEncoder* encoder)
{   write_gif_code(encoder, encoder->current_code);
    write_gif_code(encoder, encoder->eof_code);
    write_gif_code(encoder, FLUSH_OUTPUT);
}

MODULE UBYTE getred(int whichcolourset, int whichpen)
{   UBYTE rc;

    rc = (pencolours[whichcolourset][whichpen] & 0xF800) >> 8; // %#####........... -> %........#####...
    if (rc & 0x08) rc |= 7;
    return rc;
}
MODULE UBYTE getgreen(int whichcolourset, int whichpen)
{   UBYTE rc;

    rc = (pencolours[whichcolourset][whichpen] & 0x07E0) >> 3; // %.....######..... -> %........######..
    if (rc & 0x04) rc |= 3;
    return rc;
}
MODULE UBYTE getblue(int whichcolourset, int whichpen)
{   UBYTE rc;

    rc = (pencolours[whichcolourset][whichpen] & 0x001F) << 3; // %...........##### -> %........#####...
    if (rc & 0x08) rc |= 7;
    return rc;
}
